server:
  port: 8080

spring:
  application:
    name: customer-service

  banner:
    location: banner.txt

  datasource:
    url: jdbc:postgresql://localhost:5432/omni-bank-dev
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
