server:
  port: 8081

spring:
  banner:
    location: classpath:/banner.txt
  application:
    name: account-service

  datasource:
    url: jdbc:postgresql://localhost:5432/omni-bank-dev
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none

