
dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'

    implementation 'org.postgresql:postgresql:42.7.2'

    testImplementation group: 'org.mockito', name: 'mockito-junit-jupiter', version: '5.14.1'
}

bootJar{
    mainClass = 'org.omni.bank.customer.Main'
}
